USE workshop;

INSERT INTO products (name, category_id, brand, price, discount, stock, description, long_description, image, gallery_images, status) VALUES
('Essence Mascara Lash Princess',1,'Essence',9.99,1.00,99,'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.','Buy Essence Mascara Lash Princess by Essence. Designed for modern online shoppers, this beauty item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_01.jpg','uploads/products/gallery/gallery_001.jpg,uploads/products/gallery/gallery_002.jpg,uploads/products/gallery/gallery_003.jpg,uploads/products/gallery/gallery_004.jpg,uploads/products/gallery/gallery_005.jpg','Active'),
('Eyeshadow Palette with Mirror',1,'Glamour Beauty',19.99,18.19,34,'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.','Buy Eyeshadow Palette with Mirror by Glamour Beauty. Designed for modern online shoppers, this beauty item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_02.jpg','uploads/products/gallery/gallery_006.jpg,uploads/products/gallery/gallery_007.jpg,uploads/products/gallery/gallery_008.jpg,uploads/products/gallery/gallery_009.jpg,uploads/products/gallery/gallery_010.jpg,uploads/products/gallery/gallery_011.jpg','Active'),
('Powder Canister',1,'Velvet Touch',14.99,9.84,89,'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.','Buy Powder Canister by Velvet Touch. Designed for modern online shoppers, this beauty item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_03.jpg','uploads/products/gallery/gallery_012.jpg,uploads/products/gallery/gallery_013.jpg,uploads/products/gallery/gallery_014.jpg,uploads/products/gallery/gallery_015.jpg,uploads/products/gallery/gallery_016.jpg','Active'),
('Red Lipstick',1,'Chic Cosmetics',12.99,12.16,91,'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.','Buy Red Lipstick by Chic Cosmetics. Designed for modern online shoppers, this beauty item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_04.jpg','uploads/products/gallery/gallery_017.jpg,uploads/products/gallery/gallery_018.jpg,uploads/products/gallery/gallery_019.jpg,uploads/products/gallery/gallery_020.jpg,uploads/products/gallery/gallery_021.jpg,uploads/products/gallery/gallery_022.jpg','Active'),
('Red Nail Polish',1,'Nail Couture',8.99,0.90,79,'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.','Buy Red Nail Polish by Nail Couture. Designed for modern online shoppers, this beauty item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_05.jpg','uploads/products/gallery/gallery_023.jpg,uploads/products/gallery/gallery_024.jpg,uploads/products/gallery/gallery_025.jpg,uploads/products/gallery/gallery_026.jpg,uploads/products/gallery/gallery_027.jpg','Active'),
('Calvin Klein CK One',2,'Calvin Klein',49.99,1.89,29,'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.','Buy Calvin Klein CK One by Calvin Klein. Designed for modern online shoppers, this fragrances item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_06.jpg','uploads/products/gallery/gallery_028.jpg,uploads/products/gallery/gallery_029.jpg,uploads/products/gallery/gallery_030.jpg,uploads/products/gallery/gallery_031.jpg,uploads/products/gallery/gallery_032.jpg,uploads/products/gallery/gallery_033.jpg','Active'),
('Chanel Coco Noir Eau De',2,'Chanel',129.99,16.51,58,'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.','Buy Chanel Coco Noir Eau De by Chanel. Designed for modern online shoppers, this fragrances item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_07.jpg','uploads/products/gallery/gallery_034.jpg,uploads/products/gallery/gallery_035.jpg,uploads/products/gallery/gallery_036.jpg,uploads/products/gallery/gallery_037.jpg,uploads/products/gallery/gallery_038.jpg','Active'),
('Dior J''adore',2,'Dior',89.99,14.72,98,'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.','Buy Dior J''adore by Dior. Designed for modern online shoppers, this fragrances item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_08.jpg','uploads/products/gallery/gallery_039.jpg,uploads/products/gallery/gallery_040.jpg,uploads/products/gallery/gallery_041.jpg,uploads/products/gallery/gallery_042.jpg,uploads/products/gallery/gallery_043.jpg,uploads/products/gallery/gallery_044.jpg','Active'),
('Dolce Shine Eau de',2,'Dolce & Gabbana',69.99,0.62,4,'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.','Buy Dolce Shine Eau de by Dolce & Gabbana. Designed for modern online shoppers, this fragrances item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_09.jpg','uploads/products/gallery/gallery_045.jpg,uploads/products/gallery/gallery_046.jpg,uploads/products/gallery/gallery_047.jpg,uploads/products/gallery/gallery_048.jpg,uploads/products/gallery/gallery_049.jpg','Active'),
('Gucci Bloom Eau de',2,'Gucci',79.99,14.39,91,'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.','Buy Gucci Bloom Eau de by Gucci. Designed for modern online shoppers, this fragrances item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_10.jpg','uploads/products/gallery/gallery_050.jpg,uploads/products/gallery/gallery_051.jpg,uploads/products/gallery/gallery_052.jpg,uploads/products/gallery/gallery_053.jpg,uploads/products/gallery/gallery_054.jpg,uploads/products/gallery/gallery_055.jpg','Active'),
('Annibale Colombo Bed',3,'Annibale Colombo',1899.99,8.57,88,'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.','Buy Annibale Colombo Bed by Annibale Colombo. Designed for modern online shoppers, this furniture item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_11.jpg','uploads/products/gallery/gallery_056.jpg,uploads/products/gallery/gallery_057.jpg,uploads/products/gallery/gallery_058.jpg,uploads/products/gallery/gallery_059.jpg,uploads/products/gallery/gallery_060.jpg','Active'),
('Annibale Colombo Sofa',3,'Annibale Colombo',2499.99,14.4,60,'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.','Buy Annibale Colombo Sofa by Annibale Colombo. Designed for modern online shoppers, this furniture item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_12.jpg','uploads/products/gallery/gallery_061.jpg,uploads/products/gallery/gallery_062.jpg,uploads/products/gallery/gallery_063.jpg,uploads/products/gallery/gallery_064.jpg,uploads/products/gallery/gallery_065.jpg,uploads/products/gallery/gallery_066.jpg','Active'),
('Bedside Table African Cherry',3,'Furniture Co.',299.99,19.09,64,'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.','Buy Bedside Table African Cherry by Furniture Co.. Designed for modern online shoppers, this furniture item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_13.jpg','uploads/products/gallery/gallery_067.jpg,uploads/products/gallery/gallery_068.jpg,uploads/products/gallery/gallery_069.jpg,uploads/products/gallery/gallery_070.jpg,uploads/products/gallery/gallery_071.jpg','Active'),
('Knoll Saarinen Executive Conference Chair',3,'Knoll',499.99,2.01,26,'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.','Buy Knoll Saarinen Executive Conference Chair by Knoll. Designed for modern online shoppers, this furniture item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_14.jpg','uploads/products/gallery/gallery_072.jpg,uploads/products/gallery/gallery_073.jpg,uploads/products/gallery/gallery_074.jpg,uploads/products/gallery/gallery_075.jpg,uploads/products/gallery/gallery_076.jpg,uploads/products/gallery/gallery_077.jpg','Active'),
('Wooden Bathroom Sink With Mirror',3,'Bath Trends',799.99,8.8,7,'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.','Buy Wooden Bathroom Sink With Mirror by Bath Trends. Designed for modern online shoppers, this furniture item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_15.jpg','uploads/products/gallery/gallery_078.jpg,uploads/products/gallery/gallery_079.jpg,uploads/products/gallery/gallery_080.jpg,uploads/products/gallery/gallery_081.jpg,uploads/products/gallery/gallery_082.jpg','Active'),
('Apple',4,'Generic',1.99,0.20,8,'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.','Buy Apple by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_16.jpg','uploads/products/gallery/gallery_083.jpg,uploads/products/gallery/gallery_084.jpg,uploads/products/gallery/gallery_085.jpg,uploads/products/gallery/gallery_086.jpg,uploads/products/gallery/gallery_087.jpg,uploads/products/gallery/gallery_088.jpg','Active'),
('Beef Steak',4,'Generic',12.99,9.61,86,'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.','Buy Beef Steak by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_17.jpg','uploads/products/gallery/gallery_089.jpg,uploads/products/gallery/gallery_090.jpg,uploads/products/gallery/gallery_091.jpg,uploads/products/gallery/gallery_092.jpg,uploads/products/gallery/gallery_093.jpg','Active'),
('Cat Food',4,'Generic',8.99,0.90,46,'Nutritious cat food formulated to meet the dietary needs of your feline friend.','Buy Cat Food by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_18.jpg','uploads/products/gallery/gallery_094.jpg,uploads/products/gallery/gallery_095.jpg,uploads/products/gallery/gallery_096.jpg,uploads/products/gallery/gallery_097.jpg,uploads/products/gallery/gallery_098.jpg,uploads/products/gallery/gallery_099.jpg','Active'),
('Chicken Meat',4,'Generic',9.99,1.00,97,'Fresh and tender chicken meat, suitable for various culinary preparations.','Buy Chicken Meat by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_19.jpg','uploads/products/gallery/gallery_100.jpg,uploads/products/gallery/gallery_101.jpg,uploads/products/gallery/gallery_102.jpg,uploads/products/gallery/gallery_103.jpg,uploads/products/gallery/gallery_104.jpg','Active'),
('Cooking Oil',4,'Generic',4.99,0.50,10,'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.','Buy Cooking Oil by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_20.jpg','uploads/products/gallery/gallery_105.jpg,uploads/products/gallery/gallery_106.jpg,uploads/products/gallery/gallery_107.jpg,uploads/products/gallery/gallery_108.jpg,uploads/products/gallery/gallery_109.jpg,uploads/products/gallery/gallery_110.jpg','Active'),
('Cucumber',4,'Generic',1.49,0.16,84,'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.','Buy Cucumber by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_21.jpg','uploads/products/gallery/gallery_111.jpg,uploads/products/gallery/gallery_112.jpg,uploads/products/gallery/gallery_113.jpg,uploads/products/gallery/gallery_114.jpg,uploads/products/gallery/gallery_115.jpg','Active'),
('Dog Food',4,'Generic',10.99,10.27,71,'Specially formulated dog food designed to provide essential nutrients for your canine companion.','Buy Dog Food by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_22.jpg','uploads/products/gallery/gallery_116.jpg,uploads/products/gallery/gallery_117.jpg,uploads/products/gallery/gallery_118.jpg,uploads/products/gallery/gallery_119.jpg,uploads/products/gallery/gallery_120.jpg,uploads/products/gallery/gallery_121.jpg','Active'),
('Eggs',4,'Generic',2.99,0.30,9,'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.','Buy Eggs by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_23.jpg','uploads/products/gallery/gallery_122.jpg,uploads/products/gallery/gallery_123.jpg,uploads/products/gallery/gallery_124.jpg,uploads/products/gallery/gallery_125.jpg,uploads/products/gallery/gallery_126.jpg','Active'),
('Fish Steak',4,'Generic',14.99,4.23,74,'Quality fish steak, suitable for grilling, baking, or pan-searing.','Buy Fish Steak by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_24.jpg','uploads/products/gallery/gallery_127.jpg,uploads/products/gallery/gallery_128.jpg,uploads/products/gallery/gallery_129.jpg,uploads/products/gallery/gallery_130.jpg,uploads/products/gallery/gallery_131.jpg,uploads/products/gallery/gallery_132.jpg','Active'),
('Green Bell Pepper',4,'Generic',1.29,0.16,33,'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.','Buy Green Bell Pepper by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_25.jpg','uploads/products/gallery/gallery_133.jpg,uploads/products/gallery/gallery_134.jpg,uploads/products/gallery/gallery_135.jpg,uploads/products/gallery/gallery_136.jpg,uploads/products/gallery/gallery_137.jpg','Active'),
('Green Chili Pepper',4,'Generic',0.99,0.10,3,'Spicy green chili pepper, ideal for adding heat to your favorite recipes.','Buy Green Chili Pepper by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_26.jpg','uploads/products/gallery/gallery_138.jpg,uploads/products/gallery/gallery_139.jpg,uploads/products/gallery/gallery_140.jpg,uploads/products/gallery/gallery_141.jpg,uploads/products/gallery/gallery_142.jpg,uploads/products/gallery/gallery_143.jpg','Active'),
('Honey Jar',4,'Generic',6.99,0.70,34,'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.','Buy Honey Jar by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_27.jpg','uploads/products/gallery/gallery_144.jpg,uploads/products/gallery/gallery_145.jpg,uploads/products/gallery/gallery_146.jpg,uploads/products/gallery/gallery_147.jpg,uploads/products/gallery/gallery_148.jpg','Active'),
('Ice Cream',4,'Generic',5.49,0.55,27,'Creamy and delicious ice cream, available in various flavors for a delightful treat.','Buy Ice Cream by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_28.jpg','uploads/products/gallery/gallery_149.jpg,uploads/products/gallery/gallery_150.jpg,uploads/products/gallery/gallery_151.jpg,uploads/products/gallery/gallery_152.jpg,uploads/products/gallery/gallery_153.jpg,uploads/products/gallery/gallery_154.jpg','Active'),
('Juice',4,'Generic',3.99,0.40,50,'Refreshing fruit juice, packed with vitamins and great for staying hydrated.','Buy Juice by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_29.jpg','uploads/products/gallery/gallery_155.jpg,uploads/products/gallery/gallery_156.jpg,uploads/products/gallery/gallery_157.jpg,uploads/products/gallery/gallery_158.jpg,uploads/products/gallery/gallery_159.jpg','Active'),
('Kiwi',4,'Generic',2.49,0.25,99,'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.','Buy Kiwi by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_30.jpg','uploads/products/gallery/gallery_160.jpg,uploads/products/gallery/gallery_161.jpg,uploads/products/gallery/gallery_162.jpg,uploads/products/gallery/gallery_163.jpg,uploads/products/gallery/gallery_164.jpg,uploads/products/gallery/gallery_165.jpg','Active'),
('Lemon',4,'Generic',0.79,0.08,31,'Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.','Buy Lemon by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_31.jpg','uploads/products/gallery/gallery_166.jpg,uploads/products/gallery/gallery_167.jpg,uploads/products/gallery/gallery_168.jpg,uploads/products/gallery/gallery_169.jpg,uploads/products/gallery/gallery_170.jpg','Active'),
('Milk',4,'Generic',3.49,0.35,27,'Fresh and nutritious milk, a staple for various recipes and daily consumption.','Buy Milk by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_32.jpg','uploads/products/gallery/gallery_171.jpg,uploads/products/gallery/gallery_172.jpg,uploads/products/gallery/gallery_173.jpg,uploads/products/gallery/gallery_174.jpg,uploads/products/gallery/gallery_175.jpg,uploads/products/gallery/gallery_176.jpg','Active'),
('Mulberry',4,'Generic',4.99,0.50,99,'Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.','Buy Mulberry by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_33.jpg','uploads/products/gallery/gallery_177.jpg,uploads/products/gallery/gallery_178.jpg,uploads/products/gallery/gallery_179.jpg,uploads/products/gallery/gallery_180.jpg,uploads/products/gallery/gallery_181.jpg','Active'),
('Nescafe Coffee',4,'Generic',7.99,1.59,57,'Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.','Buy Nescafe Coffee by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_34.jpg','uploads/products/gallery/gallery_182.jpg,uploads/products/gallery/gallery_183.jpg,uploads/products/gallery/gallery_184.jpg,uploads/products/gallery/gallery_185.jpg,uploads/products/gallery/gallery_186.jpg,uploads/products/gallery/gallery_187.jpg','Active'),
('Potatoes',4,'Generic',2.29,0.23,13,'Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.','Buy Potatoes by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_35.jpg','uploads/products/gallery/gallery_188.jpg,uploads/products/gallery/gallery_189.jpg,uploads/products/gallery/gallery_190.jpg,uploads/products/gallery/gallery_191.jpg,uploads/products/gallery/gallery_192.jpg','Active'),
('Protein Powder',4,'Generic',19.99,7.59,80,'Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.','Buy Protein Powder by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_36.jpg','uploads/products/gallery/gallery_193.jpg,uploads/products/gallery/gallery_194.jpg,uploads/products/gallery/gallery_195.jpg,uploads/products/gallery/gallery_196.jpg,uploads/products/gallery/gallery_197.jpg,uploads/products/gallery/gallery_198.jpg','Active'),
('Red Onions',4,'Generic',1.99,0.20,82,'Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.','Buy Red Onions by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_37.jpg','uploads/products/gallery/gallery_199.jpg,uploads/products/gallery/gallery_200.jpg,uploads/products/gallery/gallery_201.jpg,uploads/products/gallery/gallery_202.jpg,uploads/products/gallery/gallery_203.jpg','Active'),
('Rice',4,'Generic',5.99,0.60,59,'High-quality rice, a staple for various cuisines and a versatile base for many dishes.','Buy Rice by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_38.jpg','uploads/products/gallery/gallery_204.jpg,uploads/products/gallery/gallery_205.jpg,uploads/products/gallery/gallery_206.jpg,uploads/products/gallery/gallery_207.jpg,uploads/products/gallery/gallery_208.jpg,uploads/products/gallery/gallery_209.jpg','Active'),
('Soft Drinks',4,'Generic',1.99,0.20,53,'Assorted soft drinks in various flavors, perfect for refreshing beverages.','Buy Soft Drinks by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_39.jpg','uploads/products/gallery/gallery_210.jpg,uploads/products/gallery/gallery_211.jpg,uploads/products/gallery/gallery_212.jpg,uploads/products/gallery/gallery_213.jpg,uploads/products/gallery/gallery_214.jpg','Active'),
('Strawberry',4,'Generic',3.99,1.12,46,'Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.','Buy Strawberry by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_40.jpg','uploads/products/gallery/gallery_215.jpg,uploads/products/gallery/gallery_216.jpg,uploads/products/gallery/gallery_217.jpg,uploads/products/gallery/gallery_218.jpg,uploads/products/gallery/gallery_219.jpg,uploads/products/gallery/gallery_220.jpg','Active'),
('Tissue Paper Box',4,'Generic',2.49,0.25,86,'Convenient tissue paper box for everyday use, providing soft and absorbent tissues.','Buy Tissue Paper Box by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_41.jpg','uploads/products/gallery/gallery_221.jpg,uploads/products/gallery/gallery_222.jpg,uploads/products/gallery/gallery_223.jpg,uploads/products/gallery/gallery_224.jpg,uploads/products/gallery/gallery_225.jpg','Active'),
('Water',4,'Generic',0.99,0.10,53,'Pure and refreshing bottled water, essential for staying hydrated throughout the day.','Buy Water by Generic. Designed for modern online shoppers, this groceries item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_42.jpg','uploads/products/gallery/gallery_226.jpg,uploads/products/gallery/gallery_227.jpg,uploads/products/gallery/gallery_228.jpg,uploads/products/gallery/gallery_229.jpg,uploads/products/gallery/gallery_230.jpg,uploads/products/gallery/gallery_231.jpg','Active'),
('Decoration Swing',5,'Generic',59.99,10.41,47,'The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.','Buy Decoration Swing by Generic. Designed for modern online shoppers, this home-decoration item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_43.jpg','uploads/products/gallery/gallery_232.jpg,uploads/products/gallery/gallery_233.jpg,uploads/products/gallery/gallery_234.jpg,uploads/products/gallery/gallery_235.jpg,uploads/products/gallery/gallery_236.jpg','Active'),
('Family Tree Photo Frame',5,'Generic',29.99,14.87,77,'The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.','Buy Family Tree Photo Frame by Generic. Designed for modern online shoppers, this home-decoration item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_44.jpg','uploads/products/gallery/gallery_237.jpg,uploads/products/gallery/gallery_238.jpg,uploads/products/gallery/gallery_239.jpg,uploads/products/gallery/gallery_240.jpg,uploads/products/gallery/gallery_241.jpg,uploads/products/gallery/gallery_242.jpg','Active'),
('House Showpiece Plant',5,'Generic',39.99,7.46,28,'The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.','Buy House Showpiece Plant by Generic. Designed for modern online shoppers, this home-decoration item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_45.jpg','uploads/products/gallery/gallery_243.jpg,uploads/products/gallery/gallery_244.jpg,uploads/products/gallery/gallery_245.jpg,uploads/products/gallery/gallery_246.jpg,uploads/products/gallery/gallery_247.jpg','Active'),
('Plant Pot',5,'Generic',14.99,6.84,59,'The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.','Buy Plant Pot by Generic. Designed for modern online shoppers, this home-decoration item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_46.jpg','uploads/products/gallery/gallery_248.jpg,uploads/products/gallery/gallery_249.jpg,uploads/products/gallery/gallery_250.jpg,uploads/products/gallery/gallery_251.jpg,uploads/products/gallery/gallery_252.jpg,uploads/products/gallery/gallery_253.jpg','Active'),
('Table Lamp',5,'Generic',49.99,7.09,9,'The Table Lamp is a functional and decorative lighting solution for your living space. With a modern design, it provides both ambient and task lighting, enhancing the atmosphere.','Buy Table Lamp by Generic. Designed for modern online shoppers, this home-decoration item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_47.jpg','uploads/products/gallery/gallery_254.jpg,uploads/products/gallery/gallery_255.jpg,uploads/products/gallery/gallery_256.jpg,uploads/products/gallery/gallery_257.jpg,uploads/products/gallery/gallery_258.jpg','Active'),
('Bamboo Spatula',6,'Generic',7.99,2.84,37,'The Bamboo Spatula is a versatile kitchen tool made from eco-friendly bamboo. Ideal for flipping, stirring, and serving various dishes.','Buy Bamboo Spatula by Generic. Designed for modern online shoppers, this kitchen-accessories item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_48.jpg','uploads/products/gallery/gallery_259.jpg,uploads/products/gallery/gallery_260.jpg,uploads/products/gallery/gallery_261.jpg,uploads/products/gallery/gallery_262.jpg,uploads/products/gallery/gallery_263.jpg,uploads/products/gallery/gallery_264.jpg','Active'),
('Black Aluminium Cup',6,'Generic',5.99,0.60,75,'The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages. Its sleek black design adds a modern touch to your drinkware collection.','Buy Black Aluminium Cup by Generic. Designed for modern online shoppers, this kitchen-accessories item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_49.jpg','uploads/products/gallery/gallery_265.jpg,uploads/products/gallery/gallery_266.jpg,uploads/products/gallery/gallery_267.jpg,uploads/products/gallery/gallery_268.jpg,uploads/products/gallery/gallery_269.jpg','Active'),
('Black Whisk',6,'Generic',9.99,1.00,73,'The Black Whisk is a kitchen essential for whisking and beating ingredients. Its ergonomic handle and sleek design make it a practical and stylish tool.','Buy Black Whisk by Generic. Designed for modern online shoppers, this kitchen-accessories item offers reliable quality, practical value, and fast delivery support.','uploads/products/main/product_50.jpg','uploads/products/gallery/gallery_270.jpg,uploads/products/gallery/gallery_271.jpg,uploads/products/gallery/gallery_272.jpg,uploads/products/gallery/gallery_273.jpg,uploads/products/gallery/gallery_274.jpg,uploads/products/gallery/gallery_275.jpg','Active');

-- Convert inserted discount values to integer percentage rules:
-- - Some products: 0%
-- - Others: between 5% and 30%
UPDATE products
SET discount = CASE
	WHEN MOD(id, 4) = 0 THEN 0
	ELSE GREATEST(5, LEAST(30, CAST(ROUND(discount) AS UNSIGNED)))
END;

